// <auto-generated> BaseForge.CodeGen — auth.yaml 'userProfile'dan üretildi; elle düzenlemeyin (yeniden üretimde ezilir).

using System.Globalization;
using System.Text.Json;
using BaseForge.Identity.Entities;
using BaseForge.Identity.Grpc;
using Microsoft.EntityFrameworkCore;

namespace BaseForge.Identity.Profile;

/// <summary>auth.yaml <c>userProfile</c> alanlarının çalışma zamanı karşılığı (bkz. BaseForge docs/ARCH.md §6.3).</summary>
public static class UserProfile
{
    /// <summary>Alan metadata'sı — Ortak Giriş SPA'sı formları buradan çizer (<c>GET /api/account/profile-schema</c>).</summary>
    public static IReadOnlyList<UserProfileField> Fields { get; } = [];

    /// <summary>Kullanıcının profil değerleri (camelCase anahtar; enum'lar ad olarak).</summary>
    public static Dictionary<string, object?> Read(ApplicationUser user) => new(StringComparer.Ordinal);

    /// <summary>
    /// Gönderilen alanları doğrulayıp kullanıcıya uygular (kısmi güncelleme — gönderilmeyen alan değişmez). Hata varsa
    /// listeyi döner; çağıran hiçbir şey kaydetmemeli. <paramref name="asAdmin"/> değilse admin-only alanlar reddedilir.
    /// </summary>
    public static List<string> Apply(ApplicationUser user, IReadOnlyDictionary<string, JsonElement>? values, bool asAdmin)
    {
        var errors = new List<string>();
        foreach (var (key, value) in values ?? new Dictionary<string, JsonElement>())
        {
            switch (key.ToLowerInvariant())
            {
                default:
                    errors.Add($"'{key}' bilinmeyen profil alanı.");
                    break;
            }
        }

        return errors;
    }

    /// <summary><c>inToken: true</c> alanların JWT claim'leri (değeri boş olan alan atlanır).</summary>
    public static IEnumerable<KeyValuePair<string, string>> TokenClaims(ApplicationUser user) => [];

    /// <summary>Profil alanlarını gRPC <c>UserMessage</c>'a yazar.</summary>
    public static void ToProto(ApplicationUser user, UserMessage message)
    {
    }

    /// <summary>EF modeli: enum → string, maxLength.</summary>
    public static void Configure(ModelBuilder builder)
    {
    }

    /// <summary>
    /// Mevcut bir veritabanına sonradan eklenen profil alanlarının kolonlarını oluşturur (<c>EnsureCreated</c> var olan
    /// tabloyu değiştirmez). NOT NULL kolonlar default'la eklenir; kolon silme/tip değiştirme yapılmaz.
    /// </summary>
    public static Task EnsureColumnsAsync(DbContext db, CancellationToken cancellationToken = default) => Task.CompletedTask;
}

/// <summary>Bir profil alanının metadata'sı (tip: auth.yaml spec tipi; <c>adminOnly</c>: yalnızca admin düzenler).</summary>
public sealed record UserProfileField(string Name, string Type, bool Nullable, bool AdminOnly, bool InToken, int? MaxLength, string? Default, IReadOnlyList<string> Values);
