using BaseForge.API.Extensions;
using Microsoft.EntityFrameworkCore;
using Scalar.AspNetCore;
using Orders.Data;

// h2c (TLS'siz HTTP/2) desteği — container/yerel ağda düz HTTP üzerinden gRPC istemci çağrıları için.
AppContext.SetSwitch("System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport", true);

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddGrpc();
builder.Services.AddOpenApi(openApi =>
{
    // Scalar'daki "Introduction" bölümü bu bilgilerden gelir (Markdown desteklenir).
    openApi.AddDocumentTransformer((document, _, _) =>
    {
        document.Info.Title = "Orders API";
        document.Info.Version = "v1";
        document.Info.Description = "# Orders API\n\nBaseForge ile üretilen **orders** mikroservisi · _orders microservice generated by BaseForge_.\n\n## 🇹🇷 Türkçe\nBu servis **orders** bounded context'ini yönetir ve şu kaynaklar için CRUD uçları sunar: **Order, OrderItem**. Her kaynak için oluşturma, güncelleme, silme (soft delete), tekil getirme ve listeleme uçları vardır.\n\nMimari: Clean Architecture + CQRS (MediatR). Veri erişimi: EF Core (+ karmaşık sorgular için Dapper). Veritabanı: PostgreSQL (servise özel, `orders_db`). Başka servislere referanslar yalnızca ID iledir (cross-DB FK yoktur).\n\n## 🇬🇧 English\nThe **orders** microservice owns the **orders** bounded context and exposes CRUD endpoints for: **Order, OrderItem**. Each resource provides create, update, delete (soft delete), get-by-id and list endpoints.\n\nArchitecture: Clean Architecture + CQRS (MediatR). Data access: EF Core (+ Dapper for complex queries). Database: PostgreSQL (per service, `orders_db`). References to other services are ID-only (no cross-DB foreign keys).";
        return Task.CompletedTask;
    });
});
builder.Services.AddBaseForge(options =>
{
    options.UsePostgreSQL<OrdersDbContext>(
        builder.Configuration.GetConnectionString("Default")
            ?? throw new InvalidOperationException("ConnectionStrings:Default tanımlı değil."));
    options.EnableCQRS(typeof(Program).Assembly);
    options.EnableAuditLog();
    options.EnableJwt(jwt =>
    {
        jwt.Authority = "http://localhost:5090";          // merkez Identity (discovery/JWKS)
        jwt.Audience = "baseforge-api";
        jwt.RequireHttpsMetadata = false;
    });
});

// identity/User servisine gRPC istemcisi (BaseForge.CodeGen tarafından üretildi).
builder.Services.AddGrpcClient<Identity.Grpc.UserService.UserServiceClient>(o =>
    o.Address = new Uri(builder.Configuration["Grpc:Identity"]
        ?? throw new InvalidOperationException("Grpc:Identity tanımlı değil.")));
builder.Services.AddScoped<Orders.Integration.IUserClient, Orders.Integration.UserClient>();
// products/Product servisine gRPC istemcisi (BaseForge.CodeGen tarafından üretildi).
builder.Services.AddGrpcClient<Products.Grpc.ProductService.ProductServiceClient>(o =>
    o.Address = new Uri(builder.Configuration["Grpc:Products"]
        ?? throw new InvalidOperationException("Grpc:Products tanımlı değil.")));
builder.Services.AddScoped<Orders.Integration.IProductClient, Orders.Integration.ProductClient>();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    // Hızlı başlangıç: migration yerine şemayı oluştur (yalnızca geliştirme).
    // Postgres erişilemezse uygulama yine de açılır; API arayüzü görülebilir.
    try
    {
        using var scope = app.Services.CreateScope();
        scope.ServiceProvider.GetRequiredService<OrdersDbContext>().Database.EnsureCreated();
    }
    catch (Exception ex)
    {
        app.Logger.LogWarning(ex, "Veritabanı şeması oluşturulamadı (Postgres çalışıyor mu?). API arayüzü yine de açık.");
    }

    // API arayüzü: /scalar/v1 (OpenAPI: /openapi/v1.json)
    app.MapOpenApi();
    app.MapScalarApiReference(options =>
    {
        options.WithTitle("Orders API");
        options.WithTheme(ScalarTheme.Default);
        // Dark mode toggle varsayılan açık. Gizlemek için: options.HideDarkModeToggle();

        // "Ask AI" (Agent Scalar): localhost'ta key'siz ücretsiz/limitli çalışır.
        // Production'da Scalar Agent key'i ver: options.WithAgentKey("SCALAR_AGENT_KEY");
        // Veya veri gizliliği için tamamen kapat:        options.DisableAgent();
    });
}

app.UseBaseForge();
app.MapControllers();
app.MapGrpcService<Orders.Grpc.OrderGrpcService>();
app.MapGrpcService<Orders.Grpc.OrderItemGrpcService>();
app.Run();
