// <auto-generated> BaseForge.CodeGen — auth.yaml 'userProfile'dan üretildi; elle düzenlemeyin (yeniden üretimde ezilir).
#nullable enable

namespace BaseForge.Identity.Entities;

/// <summary>auth.yaml <c>userProfile</c> alanları (bkz. BaseForge docs/ARCH.md §6.3).</summary>
public sealed partial class ApplicationUser
{
}
