using System.Globalization;
using System.Text;
using BaseForge.CodeGen.Contracts;

namespace BaseForge.CodeGen.Generation;

/// <summary>
/// auth.yaml <c>userProfile</c>'dan Identity'nin profil kodunu üretir: <c>ApplicationUser</c> partial'ı (alanlar +
/// enum'lar), <c>UserProfile</c> (metadata, okuma/yazma, claim, proto eşlemesi, EF yapılandırması, şema senkronu) ve
/// <c>user.proto</c>. Profil boşsa da üretilir — dosyalar her zaman vardır, gömülü referans kod onlara bağlıdır.
/// Bkz. docs/ARCH.md §6.3.
/// </summary>
internal static class UserProfileGenerator
{
    /// <summary><c>UserMessage</c>'ın sabit alanlarından sonraki ilk proto alan numarası (1–4: id, user_name, email, full_name).</summary>
    private const int FirstProfileProtoNumber = 5;

    private sealed record Field(string Name, string Camel, PropSpec Spec, string Type, bool IsEnum, string EnumType);

    private static List<Field> Fields(UserProfileSpec? profile) =>
        (profile?.Props ?? [])
            .Select(kv =>
            {
                var name = NameUtil.Pascal(kv.Key);
                var type = kv.Value.Type.Trim().ToLowerInvariant();
                return new Field(name, NameUtil.Camel(name), kv.Value, type, TypeMap.IsEnum(type), TypeMap.EnumTypeName("User", name));
            })
            .ToList();

    /// <summary><c>identity/User</c> tüketicilerinin zengin <c>UserReference</c>'ı için sabit + profil proto alanları.</summary>
    public static List<ProtoFieldModel> ConsumerProtoFields(UserProfileSpec? profile)
    {
        var fields = new List<ProtoFieldModel>
        {
            CodeGenerator.MakeProtoField("UserName", "string", 2),
            CodeGenerator.MakeProtoField("Email", "string", 3),
            CodeGenerator.MakeProtoField("FullName", "string", 4),
        };

        var number = FirstProfileProtoNumber;
        foreach (var f in Fields(profile))
        {
            fields.Add(CodeGenerator.MakeProtoField(f.Name, f.Type, number++, f.Spec.Nullable));
        }

        return fields;
    }

    /// <summary><c>user.proto</c>: <paramref name="ns"/> hem Identity servisinin kendisi hem tüketicideki kopya için (<c>Identity</c>).</summary>
    public static string BuildProto(string ns, UserProfileSpec? profile)
    {
        var sb = new StringBuilder();
        sb.AppendLine("syntax = \"proto3\";");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"option csharp_namespace = \"{ns}.Grpc\";");
        sb.AppendLine();
        sb.AppendLine("package identity;");
        sb.AppendLine();
        sb.AppendLine("// Merkez kullanıcı entity'sine (ApplicationUser) diğer servislerin salt-okunur gRPC erişimi.");
        sb.AppendLine("// BaseForge.CodeGen auth.yaml'dan üretir (userProfile alanları 5'ten itibaren); \"identity/User\" dış");
        sb.AppendLine("// referansı olan servisler aynı auth.yaml'dan aynı dosyayı alır (bkz. docs/ARCH.md §6.3).");
        sb.AppendLine("service UserService {");
        sb.AppendLine("  rpc GetById (UserByIdRequest) returns (UserMessage);");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("message UserByIdRequest {");
        sb.AppendLine("  string id = 1;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("message UserMessage {");
        sb.AppendLine("  string id = 1;");
        sb.AppendLine("  string user_name = 2;");
        sb.AppendLine("  string email = 3;");
        sb.AppendLine("  string full_name = 4;");
        foreach (var f in ConsumerProtoFields(profile).Skip(3))
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"  {f.ProtoType} {f.ProtoName} = {f.Number};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary><c>Entities/ApplicationUser.Profile.cs</c>: profil alanları + enum tipleri.</summary>
    public static string BuildEntityPartial(string ns, UserProfileSpec? profile)
    {
        var fields = Fields(profile);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> BaseForge.CodeGen — auth.yaml 'userProfile'dan üretildi; elle düzenlemeyin (yeniden üretimde ezilir).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {ns}.Entities;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>auth.yaml <c>userProfile</c> alanları (bkz. BaseForge docs/ARCH.md §6.3).</summary>");
        sb.AppendLine("public sealed partial class ApplicationUser");
        sb.AppendLine("{");
        for (var i = 0; i < fields.Count; i++)
        {
            var f = fields[i];
            if (i > 0)
            {
                sb.AppendLine();
            }

            var nullable = f.Spec.Nullable ? "?" : string.Empty;
            var type = f.IsEnum ? f.EnumType : TypeMap.ToCSharp(f.Type);
            var init = f.IsEnum
                ? (f.Spec.Default is null ? string.Empty : $" = {f.EnumType}.{f.Spec.Default};")
                : CodeGenerator.ComputeInit(f.Spec, TypeMap.ToCSharp(f.Type));
            var editable = UserProfileSpec.IsAdminOnly(f.Spec) ? "yalnızca admin düzenler" : "kullanıcı düzenler";
            var inToken = f.Spec.InToken ? $", token claim'i: {f.Camel}" : string.Empty;
            sb.AppendLine(CultureInfo.InvariantCulture, $"    /// <summary>{f.Name} ({editable}{inToken}).</summary>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public {type}{nullable} {f.Name} {{ get; set; }}{init}");
        }

        sb.AppendLine("}");

        foreach (var f in fields.Where(f => f.IsEnum))
        {
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"/// <summary>{f.Name} değerleri (DB'de ve API'de ad olarak string saklanır).</summary>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"public enum {f.EnumType}");
            sb.AppendLine("{");
            foreach (var value in f.Spec.Values)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"    {value},");
            }

            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary><c>Profile/UserProfile.cs</c>: alan metadata'sı ve alan başına tipli okuma/yazma/eşleme kodu.</summary>
    public static string BuildProfileClass(string ns, UserProfileSpec? profile)
    {
        var fields = Fields(profile);
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> BaseForge.CodeGen — auth.yaml 'userProfile'dan üretildi; elle düzenlemeyin (yeniden üretimde ezilir).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine(CultureInfo.InvariantCulture, $"using {ns}.Entities;");
        sb.AppendLine(CultureInfo.InvariantCulture, $"using {ns}.Grpc;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine(CultureInfo.InvariantCulture, $"namespace {ns}.Profile;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>auth.yaml <c>userProfile</c> alanlarının çalışma zamanı karşılığı (bkz. BaseForge docs/ARCH.md §6.3).</summary>");
        sb.AppendLine("public static class UserProfile");
        sb.AppendLine("{");

        // Metadata
        sb.AppendLine("    /// <summary>Alan metadata'sı — Ortak Giriş SPA'sı formları buradan çizer (<c>GET /api/account/profile-schema</c>).</summary>");
        if (fields.Count == 0)
        {
            sb.AppendLine("    public static IReadOnlyList<UserProfileField> Fields { get; } = [];");
        }
        else
        {
            sb.AppendLine("    public static IReadOnlyList<UserProfileField> Fields { get; } =");
            sb.AppendLine("    [");
            foreach (var f in fields)
            {
                var values = f.Spec.Values.Count == 0 ? "[]" : "[" + string.Join(", ", f.Spec.Values.Select(Quote)) + "]";
                var maxLength = f.Spec.MaxLength?.ToString(CultureInfo.InvariantCulture) ?? "null";
                var def = f.Spec.Default is null ? "null" : Quote(f.Spec.Default);
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"        new({Quote(f.Camel)}, {Quote(f.Type)}, {Bool(f.Spec.Nullable)}, {Bool(UserProfileSpec.IsAdminOnly(f.Spec))}, {Bool(f.Spec.InToken)}, {maxLength}, {def}, {values}),");
            }

            sb.AppendLine("    ];");
        }

        sb.AppendLine();

        // Read
        sb.AppendLine("    /// <summary>Kullanıcının profil değerleri (camelCase anahtar; enum'lar ad olarak).</summary>");
        if (fields.Count == 0)
        {
            sb.AppendLine("    public static Dictionary<string, object?> Read(ApplicationUser user) => new(StringComparer.Ordinal);");
        }
        else
        {
            sb.AppendLine("    public static Dictionary<string, object?> Read(ApplicationUser user) => new(StringComparer.Ordinal)");
            sb.AppendLine("    {");
            foreach (var f in fields)
            {
                var expr = f.IsEnum ? $"user.{f.Name}{(f.Spec.Nullable ? "?" : string.Empty)}.ToString()" : $"user.{f.Name}";
                sb.AppendLine(CultureInfo.InvariantCulture, $"        [{Quote(f.Camel)}] = {expr},");
            }

            sb.AppendLine("    };");
        }

        sb.AppendLine();

        // Apply
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Gönderilen alanları doğrulayıp kullanıcıya uygular (kısmi güncelleme — gönderilmeyen alan değişmez). Hata varsa");
        sb.AppendLine("    /// listeyi döner; çağıran hiçbir şey kaydetmemeli. <paramref name=\"asAdmin\"/> değilse admin-only alanlar reddedilir.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static List<string> Apply(ApplicationUser user, IReadOnlyDictionary<string, JsonElement>? values, bool asAdmin)");
        sb.AppendLine("    {");
        sb.AppendLine("        var errors = new List<string>();");
        sb.AppendLine("        foreach (var (key, value) in values ?? new Dictionary<string, JsonElement>())");
        sb.AppendLine("        {");
        sb.AppendLine("            switch (key.ToLowerInvariant())");
        sb.AppendLine("            {");
        foreach (var f in fields)
        {
            var maxLength = f.Spec.MaxLength?.ToString(CultureInfo.InvariantCulture) ?? "null";
            var enumType = f.IsEnum ? $"typeof({f.EnumType})" : "null";
            var clrType = (f.IsEnum ? f.EnumType : TypeMap.ToCSharp(f.Type)) + (f.Spec.Nullable ? "?" : string.Empty);
            var assign = f.Spec.Nullable ? $"({clrType}){f.Camel}Value" : $"({clrType}){f.Camel}Value!";
            sb.AppendLine(CultureInfo.InvariantCulture, $"                case {Quote(f.Camel.ToLowerInvariant())}:");
            if (UserProfileSpec.IsAdminOnly(f.Spec))
            {
                sb.AppendLine("                    if (!asAdmin)");
                sb.AppendLine("                    {");
                sb.AppendLine(CultureInfo.InvariantCulture, $"                        errors.Add(\"'{f.Camel}' yalnızca admin tarafından değiştirilebilir.\");");
                sb.AppendLine("                        break;");
                sb.AppendLine("                    }");
                sb.AppendLine();
            }

            sb.AppendLine(CultureInfo.InvariantCulture,
                $"                    if (ProfileJson.TryRead(value, {Quote(f.Type)}, {Bool(f.Spec.Nullable)}, {maxLength}, {enumType}, out var {f.Camel}Value, out var {f.Camel}Error))");
            sb.AppendLine("                    {");
            sb.AppendLine(CultureInfo.InvariantCulture, $"                        user.{f.Name} = {assign};");
            sb.AppendLine("                    }");
            sb.AppendLine("                    else");
            sb.AppendLine("                    {");
            sb.AppendLine(CultureInfo.InvariantCulture, $"                        errors.Add(\"'{f.Camel}' — \" + {f.Camel}Error);");
            sb.AppendLine("                    }");
            sb.AppendLine();
            sb.AppendLine("                    break;");
        }

        sb.AppendLine("                default:");
        sb.AppendLine("                    errors.Add($\"'{key}' bilinmeyen profil alanı.\");");
        sb.AppendLine("                    break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        return errors;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Token claims
        sb.AppendLine("    /// <summary><c>inToken: true</c> alanların JWT claim'leri (değeri boş olan alan atlanır).</summary>");
        var tokenFields = fields.Where(f => f.Spec.InToken).ToList();
        if (tokenFields.Count == 0)
        {
            sb.AppendLine("    public static IEnumerable<KeyValuePair<string, string>> TokenClaims(ApplicationUser user) => [];");
        }
        else
        {
            sb.AppendLine("    public static IEnumerable<KeyValuePair<string, string>> TokenClaims(ApplicationUser user)");
            sb.AppendLine("    {");
            for (var i = 0; i < tokenFields.Count; i++)
            {
                var f = tokenFields[i];
                if (i > 0)
                {
                    sb.AppendLine();
                }

                sb.AppendLine(CultureInfo.InvariantCulture, $"        if (ProfileJson.FormatClaim(user.{f.Name}) is {{ Length: > 0 }} {f.Camel}Claim)");
                sb.AppendLine("        {");
                sb.AppendLine(CultureInfo.InvariantCulture, $"            yield return new({Quote(f.Camel)}, {f.Camel}Claim);");
                sb.AppendLine("        }");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine();

        // Proto
        sb.AppendLine("    /// <summary>Profil alanlarını gRPC <c>UserMessage</c>'a yazar.</summary>");
        if (fields.Count == 0)
        {
            sb.AppendLine("    public static void ToProto(ApplicationUser user, UserMessage message)");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine("    public static void ToProto(ApplicationUser user, UserMessage message)");
            sb.AppendLine("    {");
            foreach (var f in fields)
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"        message.{f.Name} = {ProtoTypeMap.ToProtoExpr(f.Type, $"user.{f.Name}", f.Spec.Nullable)};");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine();

        // EF model
        sb.AppendLine("    /// <summary>EF modeli: enum → string, maxLength.</summary>");
        sb.AppendLine("    public static void Configure(ModelBuilder builder)");
        sb.AppendLine("    {");
        var configured = fields.Where(f => f.IsEnum || f.Spec.MaxLength is not null).ToList();
        if (configured.Count > 0)
        {
            sb.AppendLine("        var user = builder.Entity<ApplicationUser>();");
            foreach (var f in configured)
            {
                var chain = f.IsEnum ? ".HasConversion<string>()" : string.Empty;
                if (f.Spec.MaxLength is { } max)
                {
                    chain += $".HasMaxLength({max.ToString(CultureInfo.InvariantCulture)})";
                }

                sb.AppendLine(CultureInfo.InvariantCulture, $"        user.Property(u => u.{f.Name}){chain};");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // Schema sync
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Mevcut bir veritabanına sonradan eklenen profil alanlarının kolonlarını oluşturur (<c>EnsureCreated</c> var olan");
        sb.AppendLine("    /// tabloyu değiştirmez). NOT NULL kolonlar default'la eklenir; kolon silme/tip değiştirme yapılmaz.");
        sb.AppendLine("    /// </summary>");
        if (fields.Count == 0)
        {
            sb.AppendLine("    public static Task EnsureColumnsAsync(DbContext db, CancellationToken cancellationToken = default) => Task.CompletedTask;");
        }
        else
        {
            sb.AppendLine("    public static async Task EnsureColumnsAsync(DbContext db, CancellationToken cancellationToken = default)");
            sb.AppendLine("    {");
            foreach (var f in fields)
            {
                var sql = $"ALTER TABLE \"AspNetUsers\" ADD COLUMN IF NOT EXISTS \"{f.Name}\" {ColumnType(f)}{ColumnConstraint(f)};";
                sb.AppendLine(CultureInfo.InvariantCulture, $"        await ProfileJson.ExecuteDdlAsync(db, {CSharpVerbatim(sql)}, cancellationToken);");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Bir profil alanının metadata'sı (tip: auth.yaml spec tipi; <c>adminOnly</c>: yalnızca admin düzenler).</summary>");
        sb.AppendLine("public sealed record UserProfileField(string Name, string Type, bool Nullable, bool AdminOnly, bool InToken, int? MaxLength, string? Default, IReadOnlyList<string> Values);");
        return sb.ToString();
    }

    /// <summary>EF Core (Npgsql) varsayılan eşlemesiyle aynı kolon tipi.</summary>
    private static string ColumnType(Field f) => f.Type switch
    {
        "string" or "text" => f.Spec.MaxLength is { } max ? $"character varying({max.ToString(CultureInfo.InvariantCulture)})" : "text",
        "enum" => "text",
        "int" => "integer",
        "long" => "bigint",
        "short" => "smallint",
        "decimal" => "numeric",
        "double" => "double precision",
        "float" => "real",
        "bool" => "boolean",
        "datetime" => "timestamp with time zone",
        "date" => "date",
        "guid" or "uuid" => "uuid",
        _ => "text",
    };

    /// <summary>NOT NULL kolonlar için mevcut satırları geçerli tutan DEFAULT; nullable'larda boş.</summary>
    private static string ColumnConstraint(Field f)
    {
        if (f.Spec.Nullable)
        {
            return string.Empty;
        }

        var literal = f.Type switch
        {
            "string" or "text" => SqlString(f.Spec.Default ?? string.Empty),
            "enum" => SqlString(f.Spec.Default ?? f.Spec.Values[0]),
            "int" or "long" or "short" or "decimal" or "double" or "float" => f.Spec.Default ?? "0",
            "bool" => (f.Spec.Default ?? "false").ToLowerInvariant(),
            "datetime" => "'0001-01-01 00:00:00+00'",
            "date" => "'0001-01-01'",
            "guid" or "uuid" => "'00000000-0000-0000-0000-000000000000'",
            _ => "''",
        };

        return $" NOT NULL DEFAULT {literal}";
    }

    private static string SqlString(string value) => "'" + value.Replace("'", "''", StringComparison.Ordinal) + "'";

    private static string Quote(string value) =>
        "\"" + value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal) + "\"";

    private static string CSharpVerbatim(string value) => "@\"" + value.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

    private static string Bool(bool value) => value ? "true" : "false";
}
